version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamjaboo-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always